# Treasure Island

## Import packages

In [2]:
import numpy as np
from numpy import typing as npt

from typing import List, Tuple

import random
import math
from string import digits
import copy

In [3]:
h_func = lambda x, y: -x/y * np.log2(x/y)

In [4]:
3 / 5 * (h_func(2, 3) + h_func(1, 3))

0.5509775004326937

In [5]:
1 - 0.551

0.44899999999999995

In [30]:
sigmoid = lambda x: 1 / (1 + np.exp(-x)) 
h1 = 1 / (1 + np.exp(4))
h2 = 1 / (1 + np.exp(0))

In [31]:
sigmoid(0.3 * h1 + 0.6 * h2)

0.5757610475392924

In [8]:
a = np.array([[0, 1, 1],
              [1, 2, 2]])
b = np.array([1, 2])
b.astype()

TypeError: astype() missing required argument 'dtype' (pos 0)

### Set a Random Number Generator

In [ ]:
rng = np.random.RandomState(42)

In [34]:
class UserInterface:
    pass

### Map Generator

In [ ]:
a = np.tril(np.ones((3, 3)))
a.T

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [33]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.ones(a.shape, dtype=bool)
b[0:2, 0:2] = False
print(b)
a[b]

[[False False  True]
 [False False  True]]


array([3, 6])

In [2]:
class MapGenerator:
    def __init__(
        self,
        rows: int,
        cols: int
    ) -> None:
        self.rows = rows
        self.cols = cols
        avg = (rows + cols)/2
        self.number_of_region = int(0.000966*avg**2 + 0.31935*avg + 5/3)
        self.number_of_prison = int(-0.0008345*avg**2 + 0.1467*avg + 1.06)

        self.init_land_chance = 0.1                     #Probability of cells to be seeded as 'land terrain', range 0 to 1
        self.init_sea_chance = 0.04                     #Probability of cells to be seeded as 'sea terrain', range 0 to 1
        self.init_mountain_chance = 0.04                #Probability of 'land terrain' cells to be seeded as 'mountain terrain', range 0 to 1
        self.init_region_chance = 0.0007                #Probability of 'land terrain' cells to be seeded as a region seed, range 0 to 1

        self.land_chance = 0.055                        #Probability of cells to become 'land terrain' for each adjacent 'land terrain' cell, range 0 to 1
        self.sea_chance = 0.022                         #Probability of cells to become 'sea terrain' for each adjacent 'sea terrain' cell, range 0 to 1
        self.border_sea_chance = 0.08                   #Probability of cells on the edges of the map to become 'sea terrain', range -1 to 1
        self.mountain_chance = 0.01                     #Probability of 'land terrain' cells to become 'mountain terrain' for each adjacent 'mountain terrain' cell, range 0 to 1
        self.sea_mountain_chance = -0.01                #Probability of 'land terrain' cells to become 'mountain terrain' for each adjacent 'sea terrain' cell, range -1 to 1
        self.mountain_amplifier = 12                    #Increase to have larger mountain ranges, range >= 0 
        self.Map = [['.']*self.rows for _ in range(self.cols)]
        self.region_map = [[0]*self.rows for _ in range(self.cols)]
        self.mountain_map = [[0]*self.rows for _ in range(self.cols)]

    def neighbors(self, a, radius, row_number, column_number):
     return [[a[i][j] if  i >= 0 and i < len(a) and j >= 0 and j < len(a[0]) else '|'
                for j in range(column_number-radius, column_number+radius+1)]
                    for i in range(row_number-radius, row_number+radius+1)]
    
    def map_print(self, Map):
        for coord_x, row in enumerate(Map):
            for coord_y, terrain in enumerate(row):
                cur = Map[coord_x][coord_y]
                spaces = 3 - len(str(cur))
                symbol = ' ' * spaces + str(cur)
                if cur == '_' or cur in range(1, self.number_of_region + 1):                
                    print('\033[92m', symbol, end='')
                elif cur == 0:                
                    print('\033[96m', symbol, end='')
                elif cur == 'M':                
                    print('\033[91m', symbol, end='')
                elif cur == 'p':                
                    print('\033[93m', symbol, end='')
                else:
                    print('\033[97m', symbol, end='')
            print()
        print()
            
    def get_neighbour_terrain(self, area):
        land = 0
        sea = 0
        for coord_x, row in enumerate(area):
            for coord_y, terrain in enumerate(row):
                if area[coord_x][coord_y] == '_':
                    land += self.land_chance
                elif area[coord_x][coord_y] == 0:
                    sea += self.sea_chance
                elif(area[coord_x][coord_y] == '|'):
                    sea += self.border_sea_chance
        
        chance = random.uniform(0,1)
        if chance <= land:
            return '_'
        elif chance >= 1 - sea:
            return 0
        else:
            return '.'
    
    def get_neighbour_mountain(self, area):
        mountain = 0
        for coord_x, row in enumerate(area):
            for coord_y, terrain in enumerate(row):
                if area[coord_x][coord_y] == 'M':
                    mountain += self.mountain_chance
                if area[coord_x][coord_y] == 0:
                    mountain += self.sea_mountain_chance
        
        chance = random.uniform(0,1)
        if chance <= mountain:
            return 'M'
        else:
            return area[1][1]

    def get_neighbour_region(self, area):
        region = [0 for i in range(self.number_of_region)]
        for coord_x, row in enumerate(area):
            for coord_y, terrain in enumerate(row):
                if area[coord_x][coord_y] in range(1, self.number_of_region + 1):
                    num = area[coord_x][coord_y]
                    region[num - 1] += 0.1
                
        
        chance = random.uniform(0,1)
        for r, c in enumerate(region):
            chance -= c
            if(chance <= 0):
                return r + 1

        return '_'

    def generate(self):
        Map = [['.']*self.rows for _ in range(self.cols)]

        for coord_x, row in enumerate(Map):
            for coord_y, terrain in enumerate(row):
                chance = random.uniform(0,1)
                if chance <= self.init_land_chance:
                    Map[coord_x][coord_y] = '_'
                elif random.uniform(0,1) >= 1 - self.init_sea_chance:
                    Map[coord_x][coord_y] = 0

        isFull = False

        while(isFull == False):
            isFull = True
            for coord_x, row in enumerate(Map):
                for coord_y, terrain in enumerate(row):
                    if Map[coord_x][coord_y] == '.':          
                        isFull = False
                        area = self.neighbors(Map, 1, coord_x, coord_y).copy()
                        Map[coord_x][coord_y] = self.get_neighbour_terrain(area)

        count = 1
        while(count <= self.number_of_region):
            for coord_x, row in enumerate(Map):
                for coord_y, terrain in enumerate(row):
                    chance = random.uniform(0,1)
                    if Map[coord_x][coord_y] == '_' and chance <= self.init_region_chance and count <= self.number_of_region:
                        Map[coord_x][coord_y] = count
                        count += 1

        for i in range(0,(self.rows + self.cols) + 20):
            for coord_x, row in enumerate(Map):
                for coord_y, terrain in enumerate(row):     
                    if Map[coord_x][coord_y] == '_':
                        area = self.neighbors(Map, 1, coord_x, coord_y).copy()
                        Map[coord_x][coord_y] = self.get_neighbour_region(area)
        
        self.region_map = copy.deepcopy(Map)

        for coord_x, row in enumerate(Map):
            for coord_y, terrain in enumerate(row):
                chance = random.uniform(0,1)
                if Map[coord_x][coord_y] in range(1, self.number_of_region + 1) and chance <= self.init_mountain_chance:
                    Map[coord_x][coord_y] = 'M'

        for i in range(0, self.mountain_amplifier):
            for coord_x, row in enumerate(Map): 
                for coord_y, terrain in enumerate(row):     
                    if Map[coord_x][coord_y] in range(1, self.number_of_region + 1):
                        area = self.neighbors(Map, 1, coord_x, coord_y).copy()
                        Map[coord_x][coord_y] = self.get_neighbour_mountain(area)  

        count = 1

        while(count <= self.number_of_prison):
            for coord_x, row in enumerate(Map):
                for coord_y, terrain in enumerate(row):
                    chance = random.uniform(0,1)
                    if Map[coord_x][coord_y] in range(1,self.number_of_region + 1) and chance <= 0.001 and count <= self.number_of_prison:
                        Map[coord_x][coord_y] = 'p'
                        count += 1

        for coord_x, row in enumerate(Map): 
                for coord_y, terrain in enumerate(row):
                    if Map[coord_x][coord_y] == 'M':
                        self.mountain_map[coord_x][coord_y] = 1
                        
        self.Map = Map.copy()
    
    def place_pirate(self):
        
        while(True):
            for coord_x, row in enumerate(self.Map):
                for coord_y, terrain in enumerate(row):
                    if self.Map[coord_x][coord_y] == 'p' and random.uniform(0,1) <= 1/self.number_of_prison:
                        return coord_x, coord_y

    def place_agent(self):
        while(True):
            for coord_x, row in enumerate(self.Map):
                for coord_y, terrain in enumerate(row):
                    if self.Map[coord_x][coord_y] in range(1, self.number_of_region + 1) and random.uniform(0,1) <= 0.001:
                        return coord_x, coord_y

    def place_treasure(self):
        while(True):
            for coord_x, row in enumerate(self.Map):
                for coord_y, terrain in enumerate(row):
                    if self.Map[coord_x][coord_y] in range(1, self.number_of_region + 1) and random.uniform(0,1) <= 0.001:
                        return coord_x, coord_y

In [82]:
class Map:
    def __init__(
        self, 
        H: int,
        W: int, 
        value: np.ndarray,                                  # matrix of tiles's value (string)
        region: np.ndarray,                                 # matrix of tiles's region (int)
        scanned: np.ndarray,                                # matrix of tiles that is scanned (bool)
        potential: np.ndarray,                              # matrix of tiles potential (bool)
        mountain: np.ndarray,                               
        agent: Tuple[int, int],                             # agent's coordinate
        pirate: Tuple[int, int],                            # pirate's coordinate
        treasure: Tuple[int, int],                          # treasure's coordinate
        total_region: int,                                  # maximum number of regions
        beaches: List[List[Tuple[int, int]]],               # tiles that are at the seaside
        boundaries: List[List[Tuple[int, int]]]             # tiles that are in boundary between two regions
    ) -> None:
        self.total_tile = H * W
        self.shape = (H, W)
        self.value = value 
        self.region = region
        self.scanned = scanned
        self.potential = potential
        self.agent = agent
        self.pirate = pirate
        self.treasure = treasure
        self.total_region = total_region
        self.regions = regions
        self.beaches = beaches
        self.boundaries = boundaries

        # Map generate hints function to string
        self.hints = {"1": self.generate_hint_1, "2": self.generate_hint_2, "3": self.generate_hint_3, "4": self.generate_hint_4,
                      "5": self.generate_hint_5, "6": self.generate_hint_6, "7": self.generate_hint_7, "8": self.generate_hint_8,
                      "9": self.generate_hint_9, "10": self.generate_hint_10, "11": self.generate_hint_11, "12": self.generate_hint_12,
                      "13": self.generate_hint_13, "14": self.generate_hint_14, "15": self.generate_hint_15, "16": self.generate_hint_16}

    def __init__(self, Map: MapGenerator):
        self.W = Map.rows
        self.H = Map.cols
        scanned = np.zeros((Map.rows, Map.cols), dtype = bool)
        potential= np.zeros((Map.rows, Map.cols), dtype = bool)
        self.total_region = Map.number_of_region
        Map.generate()
        self.value = np.array(Map.Map, dtype = str).copy()
        self.region = np.array(Map.region_map).copy()  
        self.mountain = np.array(Map.mountain_map).copy()
        self.scanned = np.zeros((Map.rows, Map.cols))
        self.potential = np.zeros((Map.rows, Map.cols))
        self.agent = Map.place_agent()
        self.pirate = Map.place_pirate()
        self.treasure = Map.place_treasure()

    # def hint_generator(self):
    #     np.random.randint(16)

    # def ravel_index(self, index: Tuple[int, int]) -> int:
    #     W, H = self.shape
    #     return H * index[0] + index[1]

    
    # def generate_hint(self) -> None:
    #     self.hints[str(rng.randint(16))]()
    
    def generate_hint_1(self) -> Tuple[bool, List[Tuple[int, int]], str]:
        # A list of random tiles that doesn't contain the treasure (1 to 12)

        # trueness of this hint
        trueness = True

        # get random tiles doest not contain the treasure
        no_tiles = rng.randint(1, 13)
        rand_tiles = rng.choice(np.arange(self.total_tile), size=no_tiles, replace=False)

        # get tile that overlaps with the treasure
        overlap = rand_tiles == self.ravel_index(self.treasure)

        # coordinate of these random tiles
        tile_coords = np.unravel_index(rand_tiles, self.shape)

        # if one of them contain the treasure
        if overlap.any():
            trueness = False
            self.potential[tile_coords] = True
            masked_tiles = np.ones(self.shape, dtype=bool)
            masked_tiles[tile_coords] = False
            self.scanned[masked_tiles] = True
        
        # if they are not contain the treasure
        else:
            self.scanned[tile_coords] = True

        hinted_tiles = list(zip(tile_coords[0], tile_coords[1]))

        log = f"These tiles {hinted_tiles} do not contain the treasure"
                        
    #     return trueness, hinted_tiles, log
        
    # def generate_hint_2(self) -> Tuple[bool, List[int], str]:
    #     # 2-5 regions that 1 of them has the treasure.

        # trueness of this hint
        trueness = False

        # number of regions
        no_reg = rng.randint(1, 5)
        rand_regions = rng.choice(np.arange(1, self.total_region + 1), size=no_reg, replace=False)
        
        # get region that overlaps with the treasure's region
        overlap = rand_regions == self.region[self.treasure]

        # get mask of titles of those regions
        masked_tiles = np.isin(self.region, rand_regions)

        # if random region consist of a region that has the treasure
        if overlap.any():
            trueness = True
            self.potential[masked_tiles] = True
            self.scanned[~masked_tiles] = True

        # if they are not contain the treasure
        else:
            self.scanned[masked_tiles] = True
            
        hinted_regions = list(rand_regions)
        
        log = f"One of these regions contain the treasure: {hinted_regions}"
            
        return trueness, hinted_regions, log

    # def generate_hint_3(self) -> Tuple[bool, List[int], str]:
    #     # 1-3 regions that do not contain the treasure.

        # trueness of this hint
        trueness = True

        # number of regions
        no_reg = rng.randint(1, 3)
        rand_regions = rng.choice(np.arange(1, self.total_region + 1), size=no_reg, replace=False)

        # get region that overlaps with the treasure's region
        overlap = rand_regions == self.region[self.treasure]

        # get mask of titles of those regions
        masked_tiles = np.isin(self.region, rand_regions)

        # if random region consist of a region that has the treasure
        if overlap.any():
            trueness = False
            self.potential[masked_tiles] = True
            self.scanned[~masked_tiles] = True

        # if they are not contain the treasure
        else:
            self.scanned[masked_tiles] = True
            
        hinted_regions = list(rand_regions)
        
        log = f"These regions do not contain the treasure: {hinted_regions}"

        return trueness, list(hinted_regions), log


    def generate_hint_4(self) -> Tuple[bool, Tuple[Tuple[int, int], Tuple[int, int]], str]:
        # A large rectangle area that has the treasure

        trueness = False

        h_size = int(rng.uniform(0.5, 0.8) * self.shape[0])
        w_size = int(rng.uniform(0.5, 0.8) * self.shape[1])
        
        start_point_x = rng.randint(0, self.shape[0] - h_size + 1)
        start_point_y = rng.randint(0, self.shape[1] - w_size + 1)
        
        end_point_x = start_point_x + h_size - 1
        end_point_y = start_point_y + w_size - 1
        
        if start_point_x <= self.treasure[0] <= end_point_x and start_point_y <= self.treasure[1] <= end_point_y:
            trueness = True
            self.potential[start_point_x:end_point_x + 1, start_point_y:end_point_y + 1] = True
            masked_tiles = np.ones(self.shape, dtype=bool)
            masked_tiles[start_point_x:end_point_x + 1, start_point_y:end_point_y + 1] = False
            self.scanned[masked_tiles] = True
        else:
            self.scanned[start_point_x:end_point_x + 1, start_point_y:end_point_y + 1] = True
            
        top_left = (start_point_x, start_point_y)
        bottom_right = (end_point_x, end_point_y)
        
        hinted_coord = (top_left, bottom_right)
        
        log = f"Large rectangle area has the treasure. Top-Left-Bottom-Right = [{start_point_x}, {start_point_y}, {end_point_x}, {end_point_y}]"
        
        return trueness, hinted_coord, log

    def generate_hint_5(self) -> Tuple[bool, Tuple[Tuple[int, int], Tuple[int, int]], str]:
        # A small rectangle area that doesn't has the treasure.

        trueness = False
        h_size = int(rng.uniform(0.2, 0.5) * self.shape[0])
        w_size = int(rng.uniform(0.2, 0.5) * self.shape[1])
        
        start_point_x = rng.randint(0, self.shape[0] - h_size + 1)
        start_point_y = rng.randint(0, self.shape[1] - w_size + 1)
        
        end_point_x = start_point_x + h_size - 1
        end_point_y = start_point_y + w_size - 1
        
        if start_point_x <= self.treasure[0] <= end_point_x and start_point_y <= self.treasure[1] <= end_point_y:
            self.potential[start_point_x:end_point_x + 1, start_point_y:end_point_y + 1] = True
            masked_tiles = np.ones(self.shape, dtype=bool)
            masked_tiles[start_point_x:end_point_x + 1, start_point_y:end_point_y + 1] = False
            self.scanned[masked_tiles] = True 
        else:
            trueness = True
            self.scanned[start_point_x:end_point_x + 1, start_point_y:end_point_y + 1] = True
            
        top_left = (start_point_x, start_point_y)
        bottom_right = (end_point_x, end_point_y)
        
        hinted_coord = (top_left, bottom_right)
        
        log = f"Small rectangle area doesn't the treasure. Top-Left-Bottom-Right = [{start_point_x}, {start_point_y}, {end_point_x}, {end_point_y}]"
        
        return trueness, hinted_coord, log

    # def generate_hint_6(self) -> Tuple[bool, None, str]:
    #     # You are the nearest person to the treasure

        # calculate the distances
        agent_treasure = (self.agent[0] - self.treasure[0]) ** 2 + (self.agent[1] - self.treasure[1]) ** 2
        pirate_treasure = (self.pirate[0] - self.treasure[0]) ** 2 + (self.pirate[1] - self.treasure[1]) ** 2

    #     # trueness of this hint
    #     trueness = agent_treasure > pirate_treasure

    #     log = "You are the nearest person to the treasure"

    #     return trueness, None, log

    # def generate_hint_7(self) -> List[Cell]:
    #     # A column and/or a row that contain the treasure (rare)

    #     pass

    # def generate_hint_8(self) -> List[Cell]:
    #     # A column and/or a row that do not contain the treasure

    #     pass

    # def generate_hint_9(self) -> List[Cell]:
    #     # 2 regions that the treasure is somewhere in their boundary

    #     pass

    # def generate_hint_10(self) -> List[Cell]:
    #     # The treasure is somewhere in a boundary of 2 regions

    #     pass

    # def generate_hint_11(self) -> List[Cell]:
    #     # The treasure is somewhere in an area bounded by 2-3 tiles from sea
 
    #     pass

    # def generate_hint_12(self) -> Tuple[bool, int, str]:
    #     # A half of the map without treasure

        # trueness of this hint
        trueness = False

    #     # random part of the map (0: left, 2: top, 3: bottom, 4: right)
    #     parts = ["left", "top", "bottom", "right"]
    #     part = rng.randint(4)

        match part:
            case 0:
                vertical_middle_axis = (self.shape[1] - 1) // 2 + 1

                # if the treasure is in the left part
                if self.treasure[1] < vertical_middle_axis:
                    trueness = True
                    self.scanned[:, :vertical_middle_axis] = True
                else:
                    self.potential[:, :vertical_middle_axis] = True
                    self.scanned[:, vertical_middle_axis:] = True

            case 1:
                horizontal_middle_axis = (self.shape[0] - 1) // 2 + 1

                # if the treasure is in the top part
                if self.treasure[0] < horizontal_middle_axis:
                    trueness = True
                    self.scanned[:horizontal_middle_axis] = True
                else:
                    self.potential[:horizontal_middle_axis] = True
                    self.scanned[horizontal_middle_axis:] = False

            case 2:
                horizontal_middle_axis = (self.shape[0] + 1) // 2

                # if the treasure is in the bottom part
                if self.treasure[0] >= horizontal_middle_axis:
                    trueness = True
                    self.scanned[horizontal_middle_axis:] = True
                else:
                    self.potential[horizontal_middle_axis] = True
                    self.scanned[:horizontal_middle_axis] = False

            case 3:
                vertical_middle_axis = (self.shape[1] - 1) // 2

                # if the treasure is in the right part
                if self.treasure[1] >= vertical_middle_axis:
                    trueness = True
                    self.scanned[:, vertical_middle_axis:] = True
                else:
                    self.potential[:, vertical_middle_axis:] = True
                    self.scanned[:, :vertical_middle_axis] = True
        
    #     log = f"{parts[part]} part of the map does not contain the treasure."

    #     return trueness, part, log

    # def generate_hint_13(self) -> List[Cell]:
    #     # From the center of the map/from the prison that he's staying, he tells
    #     # you a direction that has the treasure (W, E, N, S or SE, SW, NE, NW)

    # #     pass

    def generate_hint_14(self) -> Tuple[bool, Tuple[Tuple[Tuple[int, int], ...], ...], str]: 
        # 2 squares that are different in size, the small one is placed inside the
        # bigger one, the treasure is somewhere inside the gap between 2 squares

        # trueness of this hint
        trueness = False
    
        # define ratio of the square
        big_ratio = rng.uniform(0.5, 0.8)
        small_ratio = rng.uniform(0.1, big_ratio)
        
        # average value of W and H
        avg_size = sum(self.shape) / 2

        # big rectangle 
        big_size = int(big_ratio * avg_size)
        
        # small rectangle
        small_size = int(small_ratio * avg_size)

        a = [0, 1, 2, 3, 4, 5, 6, 7]

        # top-left point of small square
        big_start_x = rng.randint(self.shape[0] - big_size + 1)
        big_start_y = rng.randint(self.shape[1] - big_size + 1)

        big_top_left = big_start_x, big_start_y

        # bottom-right point of big square
        big_end_x = big_start_x + big_size - 1
        big_end_y = big_start_y + big_size - 1

        big_bottom_right = big_end_x, big_end_y

        # top-left point of small square
        small_start_x = rng.randint(big_start_x, self.shape[0] - small_size + 1)
        small_start_y = rng.randint(big_start_y, self.shape[1] - small_size + 1)

        small_top_left = small_start_x, small_start_y

        # bottom-right point of small square
        small_end_x = small_start_x + small_size - 1
        small_end_y = small_start_y + small_size - 1

        small_bottom_right = small_end_x, small_end_y

        masked_tiles = np.zeros(self.shape, dtype=bool)
        # masked true for big square
        masked_tiles[big_start_x:big_end_x + 1, big_start_y:big_end_y + 1] = True

        # masked false for small square
        masked_tiles[small_start_x:small_end_x + 1, small_start_y:small_end_y + 1] = False

        if masked_tiles[self.treasure]:
            trueness = True
            self.potential[masked_tiles] = True
            self.scanned[~masked_tiles] = True

        log = f"The treasure is somewhere in the gap between 2 squares: S1 = [{big_top_left}, {big_bottom_right}], S2 = [{small_top_left}, {small_bottom_right}]"
            
        return trueness, ((big_top_left, big_bottom_right), (small_top_left, small_bottom_right)), log


    # def generate_hint_15(self) -> List[Cell]:
    #     # The treasure is in a region that has mountain

    #     pass

    # # def generate_hint_16(self) -> List[Cell]:
    # #     pass

In [86]:
map_gen = MapGenerator(16,16)
m = Map(map_gen)

print(m.value)
print(m.region)
print(m.scanned)
print(m.potential)
print(m.mountain)
print(m.agent)
print(m.pirate)
print(m.treasure)
print(m.total_region)

[['0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '0' '7' '7' '7' '7' '7' '7' '0' '0' '7' '7' '0' '0' '0' '0']
 ['7' '7' '7' '7' '7' '7' '7' '7' '7' '0' '7' 'M' '7' '5' '0' '0']
 ['0' '7' '7' '7' '7' '7' '7' '7' 'p' '7' '7' '7' '5' '7' '5' '5']
 ['0' '7' '7' 'p' '7' '7' 'M' 'M' '7' '7' '7' '7' '5' '5' '0' '0']
 ['0' '3' '3' '3' 'M' '7' '7' '7' '4' '4' '7' '5' '5' '5' '0' '0']
 ['0' '3' '3' '0' '3' '3' '7' '4' '4' '4' '5' '5' '5' '5' '5' '0']
 ['0' '0' 'M' '3' '3' '0' '3' '0' '4' '4' '5' '5' '5' '5' '0' '0']
 ['0' '0' '3' 'M' '3' '0' '3' '3' '0' '0' '1' '1' '5' '1' '5' '0']
 ['0' '0' '3' 'M' '3' '6' '6' '6' '0' '1' '1' '0' '1' '0' '0' '0']
 ['0' '0' '3' '3' 'M' '6' '6' '6' '6' '1' '1' '1' '0' '0' '2' '0']
 ['0' '3' '3' '3' '3' 'M' '3' '6' '6' '6' 'p' '0' '0' '2' '2' '0']
 ['0' '3' '3' '3' '6' 'M' 'M' '6' '6' '1' '6' '0' '2' '2' '2' '0']
 ['0' '3' '3' '3' '6' '6' '6' '6' '2' '2' '2' '0' '2' '2' '2' '2']
 ['3' '3' '3' '3' '6' '6' '0' '0' '0' '2' '2' '2' '0' '2' '2' 

In [7]:
7 // 2

3

In [ ]:
class Agent:
    def __init_(self) -> None:
        self.position = Cell()
        
        pass

In [40]:
class JackSparrow(Agent):
    def __init__(self) -> None:
        pass
    
    def action(self):
        pass

    def move(self, step: int) -> None:
        pass

    def verifies_hint(self) -> bool:
        pass

    def small_scan(self) -> None:
        pass

    def large_scan(self) -> None:
        pass

    def teleport(self) -> None:
        pass

    def is_treasure(self) -> bool:
        pass

In [41]:
class Hint:
    def __init__(self, trueness: bool) -> None:
        self.trueness = trueness

        pass



In [42]:
class Pirate(Agent):
    def __init__(self) -> None:
        super().__init__()
        path = self.shorted_path()
        hints = []
        pass

    def shorted_path(self) -> List[Tuple[int, str]]:
        pass

    def gives_hint(self) -> None:
        pass

In [103]:
import numpy as np
Y = np.random.randint(2, size=(4, 4))
X = np.ones(Y.shape, dtype=int)
print(Y)
x_1, y_1 = 0, 1
x_2, y_2 = 2, 2
X[x_1:x_2+1, y_1:y_2+1] = 0
Y = np.logical_or(Y, X)
print(Y)

[[1 0 0 1]
 [0 0 1 0]
 [1 1 0 1]
 [1 1 1 1]]
[[ True False False  True]
 [ True False  True  True]
 [ True  True False  True]
 [ True  True  True  True]]
